### ISSUE TITLE
Gists page has a bar at the top still in light theme

### ISSUE THREAD

**Issue by gregk-git** [Brettm12345/github-moonlight#13] opened 2020-04-01 12:39 UTC
**Describe the bug**
When you go to the gists page, there's a large white bar at the top.

**Expected behavior**
The bar is themed.

**Screenshots**
1. When not logged in, it takes you to the page to discover gists: https://gist.github.com/discover
   * Screenshot: https://i.imgur.com/LpXS91d.png
2. when logged in: https://gist.github.com/
   * Screenshot: https://i.imgur.com/CLZ73l0.png

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version: 81.0.4044.83 (Official Build) beta (64-bit)

**Comment by Brettm12345** [comment] 2020-04-01 13:50
I can't reproduce this issue. It might've been fixed in the last update. Could you check again

**Comment by gregk-git** [comment] 2020-04-02 07:08
I loaded the latest version, I can reproduce both (logged in and not logged in) on a Chromebook, with the style just installed.
**Screenshots:**
* Chromebook Logged in: https://i.imgur.com/NlxyVc4.png
* Chromebook incognito: https://i.imgur.com/3shKrij.png

I was also able to reproduce the issue for both conditions on `Firefox v74.0` on `Ubuntu 18.04`, with the latest version of the style. Screenshots for Firefox will be in next message.

**Comment by gregk-git** [comment] 2020-04-02 07:14
**FF screenshots:**
* not logged in: https://i.imgur.com/3zrcjsy.png
* logged in: https://i.imgur.com/gQEPLUR.png

Do note, the white bar goes away on the `https://gist.github.com/discover` page when you are logged in.
Screenshot:
* https://i.imgur.com/aZC0pBX.png

**Closed** 2020-04-12 10:58 UTC
Labels: bug
